#!/usr/bin/env bash
#
# Render a hardware-test inventory on stdout from environment variables supplied
# by the restricted `amt-lab-runner` CircleCI context.
#
# Why this exists: real AMT endpoint addresses must not live in the repository.
# tests/hardware/inventory.yml is gitignored; only inventory.yml.example is
# committed. On the lab runner this script materialises the real thing.
#
# Note what this file does NOT contain: the password and the TLS fingerprint are
# emitted as `lookup('ansible.builtin.env', ...)` expressions, not values. The
# secrets therefore never touch disk at all -- Ansible resolves them from the
# process environment at run time. That is strictly better than writing them out
# and deleting the file afterwards, and it matches the contract the qualification
# playbooks were written against (see inventory.yml.example).
#
# The group MUST be `amt_targets`: every tests/hardware/qualify_*.yml play uses
# `hosts: amt_targets`. A mismatched group name is the worst failure mode here,
# because the plays would match zero hosts and report success having done nothing.
#
# Usage:
#   ./tests/hardware/render-inventory.sh > tests/hardware/inventory.yml

set -euo pipefail

# AMT_HOST (one endpoint) and AMT_HOSTS (comma-separated) are both accepted. The
# singular form is what the lab context provides; the plural exists so a second
# machine can be qualified without reprovisioning the context.
AMT_HOSTS="${AMT_HOSTS:-${AMT_HOST:-}}"
if [ -z "${AMT_HOSTS}" ]; then
    echo "Set AMT_HOST (one endpoint) or AMT_HOSTS (comma-separated)." >&2
    exit 1
fi

AMT_TLS_FINGERPRINT="${AMT_TLS_FINGERPRINT:-}"
AMT_ALLOW_INSECURE="${AMT_ALLOW_INSECURE:-false}"

# Transport policy, mirroring the collection's own rule that a trust decision is
# always explicit. Refuse to render an inventory that would ask a module to do
# something it will reject anyway, so the failure lands here with a clear cause
# rather than midway through a playbook.
# The transport gate is applied per machine in emit_host(), because each endpoint
# has its own certificate and therefore its own pin.


emit_scalar() {
    # Single-quote and escape for YAML, so a value containing ':', '#', '{' or a
    # leading '!' cannot break the document or be reinterpreted. Applied to host
    # addresses and paths; the secrets are env lookups, never literals.
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/''/g")"
}

printf '# Generated by tests/hardware/render-inventory.sh on the lab runner.\n'
printf '# Contains no secrets: credentials resolve from the environment at run time.\n'
printf 'all:\n'
printf '  children:\n'
printf '    amt_targets:\n'
printf '      hosts:\n'

# Per-machine credentials via a numeric suffix.
#
# The first machine uses unsuffixed variables (AMT_HOST, AMT_PASSWORD, ...) and
# each additional machine appends _N: AMT_HOST_2, AMT_PASSWORD_2, and so on.
# Ports are deliberately NOT suffixed -- AMT always answers on the same ports, so
# a per-machine port would be a footgun rather than a feature.
#
# This matters because the machines genuinely differ: each presents its own
# self-signed certificate, so each needs its own reviewed fingerprint. A single
# shared AMT_TLS_FINGERPRINT across two machines cannot work, and would fail as a
# pin mismatch rather than as a clear configuration error.
#
# Credentials are emitted as env lookups, never literals, so nothing secret is
# written to disk. Each host gets host_vars naming its own variables.
emit_host() {
    suffix="$1"      # "" for the first machine, "_2", "_3", ... for the rest
    index="$2"
    host_value="$3"
    printf '        amt-lab-%02d:\n' "${index}"
    printf '          amt_host: %s\n' "$(emit_scalar "${host_value}")"
    printf "          amt_username: \"{{ lookup('ansible.builtin.env', 'AMT_USERNAME%s') | default('admin', true) }}\"\n" "${suffix}"
    printf "          amt_password: \"{{ lookup('ansible.builtin.env', 'AMT_PASSWORD%s') }}\"\n" "${suffix}"
    eval "fp=\${AMT_TLS_FINGERPRINT${suffix}:-}"
    if [ -n "${fp}" ]; then
        printf "          amt_use_tls: true\n"
        printf "          amt_allow_insecure_transport: false\n"
        printf "          amt_tls_fingerprint: \"{{ lookup('ansible.builtin.env', 'AMT_TLS_FINGERPRINT%s') }}\"\n" "${suffix}"
    elif [ "${AMT_ALLOW_INSECURE}" = "true" ]; then
        printf "          amt_use_tls: false\n"
        printf "          amt_allow_insecure_transport: true\n"
    else
        echo "Refusing to render: no AMT_TLS_FINGERPRINT${suffix} for ${host_value}, and" >&2
        echo "AMT_ALLOW_INSECURE is not 'true'. Every machine needs its own reviewed pin," >&2
        echo "because each AMT endpoint presents its own self-signed certificate." >&2
        echo "Run the hardware-observe job to read this machine's fingerprint." >&2
        exit 1
    fi

    # amt_expected_uuid activates the stage-2 identity cross-check. It stays
    # optional: qualify_readonly.yml prints the observed UUID and proceeds when it
    # is unset, which is what every run did before these values were recorded.
    #
    # Emitted as an env lookup like the credentials, for two reasons. The obvious
    # one is that nothing identifying is written to disk. The less obvious one is
    # that CircleCI masks context VALUES wherever they appear in log output, so
    # holding the platform GUID in the context censors it from the qualification
    # logs as a side effect -- which is what makes publishing those logs safe.
    #
    # Be precise about what this guard proves. Recorded from a value this
    # collection itself observed, it detects *drift*: a reused DHCP lease, an
    # inventory suffix swapped, an endpoint answering on an address that used to
    # belong to a different machine. It does NOT independently confirm the machine
    # is the one you believe it is -- that needs comparing against the booted OS's
    # own view (`sudo dmidecode -s system-uuid`, or /sys/class/dmi/id/product_uuid)
    # which nothing in CI can reach. Drift detection is still worth having, and it
    # is strictly more than the no-op it replaces.
    eval "uuid=\${AMT_EXPECTED_UUID${suffix}:-}"
    if [ -n "${uuid}" ]; then
        printf "          amt_expected_uuid: \"{{ lookup('ansible.builtin.env', 'AMT_EXPECTED_UUID%s') }}\"\n" "${suffix}"
    fi
}

index=0

# Machine 1, from AMT_HOST (or the first entry of a comma-separated AMT_HOSTS,
# which remains supported for machines that share one credential set).
for host in $(printf '%s' "${AMT_HOSTS}" | tr ',' ' '); do
    [ -n "${host}" ] || continue
    index=$((index + 1))
    if [ "${index}" -eq 1 ]; then
        emit_host "" 1 "${host}"
    else
        emit_host "_${index}" "${index}" "${host}"
    fi
done

# Additional machines declared with suffixed variables. Starts at the next index
# after whatever AMT_HOST/AMT_HOSTS produced, and stops at the first gap.
n=$((index + 1))
while : ; do
    eval "extra_host=\${AMT_HOST_${n}:-}"
    [ -n "${extra_host}" ] || break
    # Skip if AMT_HOSTS already covered this index, so the two styles can coexist
    # without emitting a machine twice.
    if [ "${n}" -gt "${index}" ]; then
        emit_host "_${n}" "${n}" "${extra_host}"
        index="${n}"
    fi
    n=$((n + 1))
done

if [ "${index}" -eq 0 ]; then
    echo "No machines to render: set AMT_HOST (and optionally AMT_HOST_2, ...)." >&2
    exit 1
fi

printf '      vars:\n'
# Ports are shared across machines by design -- AMT always listens on the same
# ports, so these stay group-level rather than per-host.
if [ -n "${AMT_PORT:-}" ]; then
    printf '        amt_port: %s\n' "${AMT_PORT}"
fi
if [ -n "${AMT_REDIRECTION_PORT:-}" ]; then
    printf '        amt_redirection_port: %s\n' "${AMT_REDIRECTION_PORT}"
fi
# Stage 5/6 media paths, only if provided. Absent is normal: those stages are run
# deliberately by a human, not from CI.
if [ -n "${AMT_TEST_ISO_PATH:-}" ]; then
    printf '        amt_test_iso_path: %s\n' "$(emit_scalar "${AMT_TEST_ISO_PATH}")"
fi
if [ -n "${AMT_TEST_IMAGE_PATH:-}" ]; then
    printf '        amt_test_image_path: %s\n' "$(emit_scalar "${AMT_TEST_IMAGE_PATH}")"
fi
