#!/usr/bin/env bash
#
# Render a hardware-test inventory on stdout from environment variables supplied
# by the restricted `amt-lab-runner` CircleCI context.
#
# Why this exists: real AMT endpoint addresses must not live in the repository.
# tests/hardware/inventory.yml is gitignored; only inventory.yml.example is
# committed. On the lab runner this script materialises the real thing.
#
# Note what this file does NOT contain: the password and the TLS fingerprint are
# emitted as `lookup('ansible.builtin.env', ...)` expressions, not values. The
# secrets therefore never touch disk at all -- Ansible resolves them from the
# process environment at run time. That is strictly better than writing them out
# and deleting the file afterwards, and it matches the contract the qualification
# playbooks were written against (see inventory.yml.example).
#
# The group MUST be `amt_targets`: every tests/hardware/qualify_*.yml play uses
# `hosts: amt_targets`. A mismatched group name is the worst failure mode here,
# because the plays would match zero hosts and report success having done nothing.
#
# Usage:
#   ./tests/hardware/render-inventory.sh > tests/hardware/inventory.yml

set -euo pipefail

# AMT_HOST (one endpoint) and AMT_HOSTS (comma-separated) are both accepted. The
# singular form is what the lab context provides; the plural exists so a second
# machine can be qualified without reprovisioning the context.
AMT_HOSTS="${AMT_HOSTS:-${AMT_HOST:-}}"
if [ -z "${AMT_HOSTS}" ]; then
    echo "Set AMT_HOST (one endpoint) or AMT_HOSTS (comma-separated)." >&2
    exit 1
fi

AMT_TLS_FINGERPRINT="${AMT_TLS_FINGERPRINT:-}"
AMT_ALLOW_INSECURE="${AMT_ALLOW_INSECURE:-false}"

# Transport policy, mirroring the collection's own rule that a trust decision is
# always explicit. Refuse to render an inventory that would ask a module to do
# something it will reject anyway, so the failure lands here with a clear cause
# rather than midway through a playbook.
if [ -z "${AMT_TLS_FINGERPRINT}" ] && [ "${AMT_ALLOW_INSECURE}" != "true" ]; then
    echo "Refusing to render: no AMT_TLS_FINGERPRINT and AMT_ALLOW_INSECURE is not 'true'." >&2
    echo "Run the hardware-observe CI job, review the fingerprint it prints, then store it" >&2
    echo "as AMT_TLS_FINGERPRINT in the amt-lab-runner context. Alternatively set" >&2
    echo "AMT_ALLOW_INSECURE=true for firmware with no TLS at all (AMT in Small Business" >&2
    echo "Mode never opens port 16993)." >&2
    exit 1
fi

if [ -n "${AMT_TLS_FINGERPRINT}" ]; then
    use_tls=true
    allow_insecure=false
else
    use_tls=false
    allow_insecure=true
fi

emit_scalar() {
    # Single-quote and escape for YAML, so a value containing ':', '#', '{' or a
    # leading '!' cannot break the document or be reinterpreted. Applied to host
    # addresses and paths; the secrets are env lookups, never literals.
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/''/g")"
}

printf '# Generated by tests/hardware/render-inventory.sh on the lab runner.\n'
printf '# Contains no secrets: credentials resolve from the environment at run time.\n'
printf 'all:\n'
printf '  children:\n'
printf '    amt_targets:\n'
printf '      hosts:\n'

index=0
for host in $(printf '%s' "${AMT_HOSTS}" | tr ',' ' '); do
    [ -n "${host}" ] || continue
    index=$((index + 1))
    printf '        amt-lab-%02d:\n' "${index}"
    printf '          amt_host: %s\n' "$(emit_scalar "${host}")"
done

if [ "${index}" -eq 0 ]; then
    echo "AMT_HOSTS produced no usable entries." >&2
    exit 1
fi

printf '      vars:\n'
printf "        amt_username: \"{{ lookup('ansible.builtin.env', 'AMT_USERNAME') | default('admin', true) }}\"\n"
printf "        amt_password: \"{{ lookup('ansible.builtin.env', 'AMT_PASSWORD') }}\"\n"
printf '        amt_use_tls: %s\n' "${use_tls}"
printf '        amt_allow_insecure_transport: %s\n' "${allow_insecure}"
if [ -n "${AMT_TLS_FINGERPRINT}" ]; then
    printf "        amt_tls_fingerprint: \"{{ lookup('ansible.builtin.env', 'AMT_TLS_FINGERPRINT') }}\"\n"
fi
# Ports are emitted only when the context sets them. Otherwise the collection
# derives 16993/16992 and 16995/16994 from the transport mode, and hardcoding a
# default here could silently drift from the collection's own.
if [ -n "${AMT_PORT:-}" ]; then
    printf '        amt_port: %s\n' "${AMT_PORT}"
fi
if [ -n "${AMT_REDIRECTION_PORT:-}" ]; then
    printf '        amt_redirection_port: %s\n' "${AMT_REDIRECTION_PORT}"
fi
# Stage 5/6 media paths, only if provided. Absent is normal: those stages are run
# deliberately by a human, not from CI.
if [ -n "${AMT_TEST_ISO_PATH:-}" ]; then
    printf '        amt_test_iso_path: %s\n' "$(emit_scalar "${AMT_TEST_ISO_PATH}")"
fi
if [ -n "${AMT_TEST_IMAGE_PATH:-}" ]; then
    printf '        amt_test_image_path: %s\n' "$(emit_scalar "${AMT_TEST_IMAGE_PATH}")"
fi
